### ISSUE TITLE
How Can I Handle the Individual Post Format “Quote”

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#12]
Hi @Tovic,

I've just dealt with your tutorial at http://mecha-cms.com/article/page-format . I have the hook in the index.php of the Shields involved.

Also the part with `Config::set` also in the index.php.

Have I now under https://mechacms.wpzweinull.ch/article/testen-des-post-formats-quote-in-mecha-v2-cms the correct Quote format reached?

I can select `Quote` in the backend of the CMS and the text is then displayed in the frontend as a quote.

Can I use the Markdown Syntax for this Post Format? The ckeditor is not displayed.

**Comment by taufik-nurrohman** [comment]
You can use Markdown Syntax for the `Quote` post format, but it is hard-coded. Simply change this part:

~~~ .php
$content = '<p>' . str_replace(["\n\n", "\n"], ['</p><p>', '<br>'], $content) . '</p>';
~~~

With this:

~~~ .php
$content = From::markdown($content);
~~~

So that the line-break-to-paragraph converter will now relies on the Markdown parser, including the strong, emphasis, and the other formats in Markdown.

**Comment by ghost** [comment]
Thank you, I have implemented and now I will test a bit.

I think we can now close this issue. Thank you!
