### ISSUE TITLE
Mecha-cms.com no longer available - what happened?

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#33]
Hi @tovic,

just wanted to call your website http://mecha-cms.com, but apparently it is not achievable. Are there problems with webhosting or is it something else?

Then I wait for your feedback.

Thank you!!

### Update 11:41 AM

I think that the webhosting is not paid for you or something like that. For your pleasure, I just donated 15 USD to you via PayPal.

Please tell me if you have the money.

I gladly made it for the Mecha Project 👍

**Comment by taufik-nurrohman** [comment]
Have just graduated from my nursing institution and I am currently attending an internship program at a hospital in the city where I live. I need to use the cost for some things, hence I have to treat _Mecha_ as a second priority.

Don&rsquo;t worry, next time I hope I can soon get the real job in the same place so that I can handle the _Mecha_ CMS costs independently. Thank you very much for your supports until now!

**Comment by ghost** [comment]
OK, I can fully understand how you proceeded. I would have done the same. Then the website will be back online soon. I need to call times in the browser.

I was very happy to help the Mecha CMS project because I like this CMS very much and I like working with it 😄

**Comment by taufik-nurrohman** [comment]
https://www.facebook.com/mecha.cms/posts/2117457425156072
